#!/usr/bin/env python3
"""Deterministically compile transparent 24/36px pixel PNGs into flash-only RGB565 RLE.

Format: one run byte, upper 5 bits = local palette index 0..31, lower
three bits = run length-1 (1..8). Role 0 is TRANSPARENT. Each image
has its own 1..31 RGB565 colors; never allocate an image buffer at runtime.
"""
from collections import Counter
from pathlib import Path
from PIL import Image
import json, math
ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/'tools/pixel_icon_assets/png'
DST=ROOT/'src/core/VqeafIconData.h'
NAMES=('wifi','bluetooth','music','files','gallery','internet','shell','recovery','settings','themes','apps','library')

def rgb565(color):
 r,g,b=color[:3];return ((r>>3)<<11)|((g>>2)<<5)|(b>>3)
def unpack565(c):
 return ((c>>11 &31)*255//31,(c>>5&63)*255//63,(c&31)*255//31)
def quantize_palette(img):
 px=list(img.get_flattened_data() if hasattr(img,"get_flattened_data") else img.getdata())
 opaque=[(r,g,b) for r,g,b,a in px if a>=128]
 distinct=Counter(map(rgb565,opaque))
 if len(distinct)<=31:
  colors=[c for c,_ in sorted(distinct.items(),key=lambda kv:(-kv[1],kv[0]))]
  mapping={c:i+1 for i,c in enumerate(colors)}
  return [0]+colors,[0 if a<128 else mapping[rgb565((r,g,b))] for r,g,b,a in px]
 # Common icons contain color noise from generated contact art. Palettize
 # only opaque pixels to avoid blending green background into white edge art.
 strip=Image.new('RGB',(len(opaque),1));strip.putdata(opaque)
 q=strip.quantize(colors=30,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
 keys=[rgb565(tuple(q.getpalette()[i*3:i*3+3])) for i in range(30)]
 # Coalesce colors which round into the same RGB565 value.
 colors=list(dict.fromkeys(keys))
 if len(colors)>31:raise ValueError('overfull icon palette')
 def nearest(c):
  r,g,b=unpack565(c); return min(range(len(colors)),key=lambda i:sum((a-b)**2 for a,b in zip((r,g,b),unpack565(colors[i]))))+1
 mapping={c:nearest(c) for c in distinct}
 return [0]+colors,[0 if a<128 else mapping[rgb565((r,g,b))] for r,g,b,a in px]
def compile_image(name,n):
 img=Image.open(SRC/f'{name}_{n}.png').convert('RGBA');assert img.size==(n,n)
 palette,indices=quantize_palette(img)
 # safety gutter is transparent for tile focus frame and backgrounds.
 safe=4 if n==36 else 3
 for y in range(n):
  for x in range(n):
   if x<safe or y<safe or x>=n-safe or y>=n-safe:
    assert indices[y*n+x]==0,(name,n,x,y,'unsafe gutter')
 runs=[]
 for y in range(n):
  x=0
  while x<n:
   z=indices[y*n+x];length=1
   while x+length<n and length<8 and indices[y*n+x+length]==z:length+=1
   runs.append((z<<3)|(length-1));x+=length
 return palette,runs,indices

def create():
 parts=['// GENERATED by tools/pixel_icon_assets/compile_pixel_icons.py from individual icon PNGs.',
        '// 5-bit local palette (RGB565), 3-bit horizontal run length (1..8).',
        '// Index 0 = transparent. Constant data remains in flash/rodata, NOT PSRAM.',
        '#pragma once','#include <stdint.h>','namespace VqeafIconData {',
        'struct Asset { uint8_t width, height; uint16_t bytes; const uint8_t *rle; const uint16_t *rgb565; uint8_t palette_len; };']
 stats={}
 for n in (24,36):
  for name in NAMES:
   pal,rr,indices=compile_image(name,n)
   def fmt(arr,conv):
    chunks=[arr[i:i+14] for i in range(0,len(arr),14)]
    return '\n'.join('  '+','.join(conv(x) for x in line)+',' for line in chunks)
   parts+= [f'static const uint8_t {name}_{n}[] = {{',fmt(rr,lambda z:f'0x{z:02X}'),'};',
           f'static const uint16_t {name}_{n}_rgb[] = {{',fmt(pal,lambda z:f'0x{z:04X}'),'};']
   stats[f'{name}_{n}']={'bytes':len(rr)+len(pal)*2,'rle_bytes':len(rr),'colors':len(pal)-1,'opaque':sum(bool(i) for i in indices),'size':n}
 for n in (24,36):
  parts.append(f'static const Asset ICONS_{n}[12] = {{')
  for name in NAMES:
   p,_,_=compile_image(name,n)
   parts.append(f'  {{{n},{n},sizeof({name}_{n}),{name}_{n},{name}_{n}_rgb,{len(p)}}},')
  parts.append('};')
 parts.append('} // namespace VqeafIconData')
 DST.write_text('\n'.join(parts)+'\n')
 info=ROOT/'tools/pixel_icon_assets/icon_build_stats.json';info.write_text(json.dumps({'total_flash_bytes':sum(d['bytes'] for d in stats.values()),'assets':stats},indent=2)+'\n')
 print('GENERATED',DST,'flash icon bytes',sum(d['bytes'] for d in stats.values()))
if __name__=='__main__':create()
