[platformio]
default_envs = esp32s3

[env:esp32s3]
board = lilka_v2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions-s3.csv
build_flags =
  -Isrc/
  -Isrc/config/
  -std=gnu++20
  -DCORE_DEBUG_LEVEL=3
  ; -DCORE_DEBUG_LEVEL=0
  -D CONFIG_SPIRAM_SUPPORT=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

check_skip_packages = yes
check_tool = cppcheck
check_severity = low, medium, high
check_flags = 
  --enable=all 
  --inconclusive 
  --suppress=badBitmaskCheck 
  --suppress=missingIncludeSystem
  --suppress=missingInclude
  --suppress=unusedFunction
  --suppress=*:*src/config/*
extra_scripts = pre:../../scripts/link_lib.py


; debug_tool = esp-builtin
; upload_protocol = esp-builtin
; debug_init_break = tbreak setup

; build_unflags =
;   -D ARDUINO_USB_CDC_ON_BOOT=1

;------------------------------------------------------------------------------
