; ESP_Browser 1.1 — real HTTP/HTTPS HTML/WML browser port tu DMAX_QQ_Browser (MRE VXP) cho E524546
; MCU: ESP32-S3-WROOM-1 N16R8 | LCD ST7789 240x320 doc | keypad Symbian 3x3+SELECT | SDMMC
[env:esp32-s3-st7789]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.filesystem = littlefs
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.arduino.cdc_on_boot = 1
board_build.partitions = huge_app.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags =
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM=1

lib_deps =
  lovyan03/LovyanGFX@^1.2.7
