#pragma once

#define UI_UPDATE_DELAY 25
#define GRAPHICS_ENABLED
#define DOUBLE_BUFFERRING

#define BUSS_FREQUENCY 40000000

#define UI_WIDTH 240
#define UI_HEIGHT 320
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define ROTATE_CANVAS false

#define SPI_PORT FSPI
#define TFT_MOSI 12
#define TFT_SCLK 48
#define TFT_MISO -1
#define TFT_RST 3
#define TFT_DC 47
#define TFT_CS 14

#define PIN_DISPLAY_BL 39
#define HAS_BL_PWM
#define DISPLAY_BL_PWM_FREQ 3000
#define DISPLAY_BL_PWM_RES 8

#define DISPLAY_ROTATION 0
#define IS_IPS_DISPLAY true
#define INVERT_COLORS false

#define BUS_TYPE Arduino_ESP32SPI
#define IS_COMMON_BUS false
#define BUS_PARAMS TFT_DC, TFT_CS, TFT_SCLK, TFT_MOSI, TFT_MISO, SPI_PORT, IS_COMMON_BUS

#define DISP_DRIVER_TYPE Arduino_ST7789
#define DISP_DRIVER_PARAMS TFT_RST, DISPLAY_ROTATION, IS_IPS_DISPLAY, DISPLAY_WIDTH, DISPLAY_HEIGHT

