[platformio]
default_envs = esp32p4

;------------------------------------------------------------------------------

; common build options
[common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_flags =
  -Isrc/
  -Isrc/config/
  -std=gnu++20
  -DCORE_DEBUG_LEVEL=3
  ; -DCORE_DEBUG_LEVEL=0
check_skip_packages = yes
check_tool = cppcheck
check_flags = 
    --enable=all 
    --inconclusive 
    --suppress=badBitmaskCheck 
    --suppress=missingIncludeSystem
    --suppress=missingInclude
    --suppress=unusedFunction
    --suppress=*:*src/config/*
check_severity = low, medium, high

;------------------------------------------------------------------------------

; ESP32 P4 environment
[env:esp32p4]
board = esp32-p4-evboard
platform = ${common.platform}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.partitions = partitions-p4.csv
build_flags =
  ${common.build_flags}
  -D CONFIG_SPIRAM_SUPPORT=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

check_skip_packages = ${common.check_skip_packages}
check_tool = ${common.check_tool}
check_flags =${common.check_flags}
extra_scripts = pre:../../scripts/link_lib.py

; build_unflags =
;   -D ARDUINO_USB_CDC_ON_BOOT=1

; debug_tool = esp-builtin
; upload_protocol = esp-builtin
; debug_init_break = tbreak setup
