[platformio]
default_envs = legacy32_e524546

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
lib_ldf_mode = deep+
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  h2zero/NimBLE-Arduino @ ^2.3.6
  jgromes/RadioLib @ ^7.1.2
  crankyoldgit/IRremoteESP8266 @ ^2.8.6
build_flags =
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/Network/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/FS/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/SPI/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/LittleFS/src"
  -I"C:/Users/admin/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src"
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MOSI=12
  -D TFT_SCLK=4
  -D TFT_CS=14
  -D TFT_DC=47
  -D TFT_RST=3
  -D TFT_BL=39
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SMOOTH_FONT=1
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=16000000
  -D USE_FSPI_PORT=1

[env:legacy32_e524546]
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_USE_MALLOC=1
  -D CORE_DEBUG_LEVEL=1
