#!/usr/bin/env python3
"""Convert the 24x24 RGBA PNG icons in assets/icon into a C header of
0x00RRGGBB arrays compatible with drawScaledRGBBitmap() (black = transparent).

Usage:
    python tools/convert_icons.py
Output:
    include/asset/bitmap_app_icons.h
"""
import glob
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "assets", "icon")
OUT = os.path.join(ROOT, "include", "asset", "bitmap_app_icons.h")

ALPHA_CUTOFF = 128  # pixels below this alpha become transparent (black)


def sanitize(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in name).lower()


def convert(path: str):
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    px = img.load()
    words = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < ALPHA_CUTOFF:
                words.append(0x000000)
            else:
                words.append((r << 16) | (g << 8) | b)
    return w, h, words


def main():
    files = sorted(glob.glob(os.path.join(SRC_DIR, "*.png")))
    if not files:
        raise SystemExit("no PNG icons found in %s" % SRC_DIR)

    lines = []
    lines.append("#ifndef BITMAP_APP_ICONS_H")
    lines.append("#define BITMAP_APP_ICONS_H")
    lines.append("")
    lines.append("// Auto-generated by tools/convert_icons.py from assets/icon/*.png")
    lines.append("// Format: 0x00RRGGBB per pixel, row-major. 0x000000 = transparent")
    lines.append("// (matches the launcher's drawScaledRGBBitmap / drawRGBBitmap).")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")

    names = []
    for f in files:
        base = os.path.splitext(os.path.basename(f))[0]
        name = sanitize(base)
        sym = "ic_" + name
        up = name.upper()
        w, h, words = convert(f)
        names.append((name, sym, up, w, h))
        lines.append("#define IC_%s_W %d" % (up, w))
        lines.append("#define IC_%s_H %d" % (up, h))
        lines.append("static const uint32_t %s[] PROGMEM = {" % sym)
        row = []
        for i, v in enumerate(words):
            row.append("0x%06x" % v)
            if (i + 1) % w == 0:
                lines.append("  " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("  " + ", ".join(row) + ",")
        lines.append("};")
        lines.append("")

    # Convenience name table (optional lookups by string).
    lines.append("struct AppIconEntry {")
    lines.append("  const char *name;")
    lines.append("  const uint32_t *data;")
    lines.append("  int w;")
    lines.append("  int h;")
    lines.append("};")
    lines.append("")
    lines.append("static const AppIconEntry APP_ICONS[] = {")
    for name, sym, up, w, h in names:
        lines.append('  {"%s", %s, IC_%s_W, IC_%s_H},' % (name, sym, up, up))
    lines.append("};")
    lines.append("static const int APP_ICONS_COUNT = %d;" % len(names))
    lines.append("")
    lines.append("#endif  // BITMAP_APP_ICONS_H")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    total = sum(w * h * 4 for _, _, _, w, h in names)
    print("Wrote %s" % OUT)
    print("Icons: %d, PROGMEM bytes: %d" % (len(names), total))
    for name, sym, up, w, h in names:
        print("  %-12s %s %dx%d" % (name, sym, w, h))


if __name__ == "__main__":
    main()
