#pragma once
#include "board_config.h"

#define UI_UPDATE_DELAY 25
#define GRAPHICS_ENABLED
#define DOUBLE_BUFFERRING

#define BUSS_FREQUENCY 40000000

#define UI_WIDTH 240
#define UI_HEIGHT 320
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define ROTATE_CANVAS false

#define SPI_PORT FSPI
#define TFT_MOSI BOARD_TFT_MOSI
#define TFT_SCLK BOARD_TFT_SCLK
#define TFT_MISO -1
#define TFT_RST BOARD_TFT_RST
#define TFT_DC BOARD_TFT_DC
#define TFT_CS BOARD_TFT_CS

#define PIN_DISPLAY_BL BOARD_TFT_BL
#define HAS_BL_PWM
#define DISPLAY_BL_PWM_FREQ 3000
#define DISPLAY_BL_PWM_RES 8

#define DISPLAY_ROTATION 0
#define IS_IPS_DISPLAY true
#define INVERT_COLORS false

#define BUS_TYPE Arduino_ESP32SPI
#define IS_COMMON_BUS false
#define BUS_PARAMS TFT_DC, TFT_CS, TFT_SCLK, TFT_MOSI, TFT_MISO, SPI_PORT, IS_COMMON_BUS

#define DISP_DRIVER_TYPE Arduino_ST7789
#define DISP_DRIVER_PARAMS TFT_RST, DISPLAY_ROTATION, IS_IPS_DISPLAY, DISPLAY_WIDTH, DISPLAY_HEIGHT
