#!/usr/bin/env python3
"""Generate Retro-Go rg_font_t bitmap font headers from a TTF (headless, no tkinter).

Usage:
  python tools/make_font.py --ttf C\\:/Windows/Fonts/tahoma.ttf --size 12 \
      --out include/fonts/lc_font_vn12.h --ranges "32-126,160-383,416-417,432-433,7840-7929"

Bitmap format matches retro-go/tools/font_converter.py:
  per glyph: code(u16 LE), yOffset, width, height, xOffset, xDelta, packed bitmap
  bit order: row-major, MSB first; bytes = ceil(w*h/8)
"""
from __future__ import annotations

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont


def parse_ranges(spec: str) -> list[int]:
    codes: set[int] = set()
    for part in spec.replace(" ", "").split(","):
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            codes.update(range(int(a, 0), int(b, 0) + 1))
        else:
            codes.add(int(part, 0))
    return sorted(codes)


def find_bbox(image: Image.Image):
    px = image.load()
    w, h = image.size
    x0, y0, x1, y1 = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            if px[x, y] >= 1:
                if x < x0:
                    x0 = x
                if y < y0:
                    y0 = y
                if x > x1:
                    x1 = x
                if y > y1:
                    y1 = y
    if x1 < 0:
        return None
    return (x0, y0, x1 + 1, y1 + 1)


def pack_bitmap(cropped: Image.Image, width: int, height: int) -> list[int]:
    bitmap: list[int] = []
    row = 0
    i = 0
    for y in range(height):
        for x in range(width):
            if i == 8:
                bitmap.append(row)
                row = 0
                i = 0
            row = (row << 1) | (1 if cropped.getpixel((x, y)) else 0)
            i += 1
    if i:
        row <<= 8 - i
        bitmap.append(row)
    need = (width * height + 7) // 8
    return bitmap[:need]


def load_glyphs(ttf: str, size: int, ranges: str, enforce: bool):
    pil = ImageFont.truetype(ttf, size)
    name = " ".join(pil.getname())
    glyphs = []
    for code in parse_ranges(ranges):
        ch = chr(code)
        # Pad so glyphs with left bearing / wide advance are not clipped.
        canvas = Image.new("1", (size * 3, size * 3), 0)
        draw = ImageDraw.Draw(canvas)
        draw.text((size, size), ch, font=pil, fill=255)
        bbox = find_bbox(canvas)
        if bbox is None:
            width = height = 0
            ox = oy = 0
            adv = 0
        else:
            x0, y0, x1, y1 = bbox
            width, height = x1 - x0, y1 - y0
            ox, oy = x0 - size, y0 - size
            if ox < 0:
                ox = 0
            if oy < 0:
                # Glyph top is above draw origin — bake into bitmap by re-crop with clamped oy.
                height += oy
                y0 -= oy
                oy = 0
                if height < 0:
                    height = 0
            try:
                adv = int(draw.textlength(ch, font=pil))
            except Exception:
                adv = width + max(ox, 0)
            if adv < width + ox:
                adv = width + max(ox, 0)
            if enforce and oy + height > size:
                if size - height >= 0:
                    oy = size - height
                else:
                    oy = 0
                    height = size
            if oy < 0:
                oy = 0
            # Re-crop from a fresh draw for exact bitmap (oy/ox already clamped >= 0).
            canvas2 = Image.new("1", (size * 3, size * 3), 0)
            draw2 = ImageDraw.Draw(canvas2)
            draw2.text((size, size), ch, font=pil, fill=255)
            box = (size + ox, size + oy, size + ox + width, size + oy + height)
            cropped = canvas2.crop(box)
            bitmap = pack_bitmap(cropped, width, height)
        if height == 0 or width == 0:
            bitmap = []
            width = height = 0
            ox = oy = 0
            adv = max(adv, size // 3) if code not in (32,) else size // 3
        glyphs.append(
            {
                "code": code,
                "ofs_y": int(oy),
                "box_w": int(width),
                "box_h": int(height),
                "ofs_x": int(ox),
                "adv_w": int(max(adv, 1)),
                "bitmap": bitmap,
            }
        )
    max_h = max((g["ofs_y"] + g["box_h"]) for g in glyphs) if glyphs else size
    return name, max(size, max_h), glyphs


def emit_c(name: str, size: int, max_h: int, glyphs, symbol: str) -> str:
    mem = sum(len(g["bitmap"]) + 7 for g in glyphs)
    lines = [
        "// Generated by tools/make_font.py — Retro-Go rg_font_t stream.",
        f"// Font: {name}  size={size}  glyphs={len(glyphs)}  ~{mem} bytes",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "#ifndef LC_FONT_TYPES_DEFINED",
        "#define LC_FONT_TYPES_DEFINED",
        "typedef struct __attribute__((packed)) {",
        "  uint16_t code;",
        "  uint8_t yOffset;",
        "  uint8_t width;",
        "  uint8_t height;",
        "  uint8_t xOffset;",
        "  uint8_t xDelta;",
        "  uint8_t data[];",
        "} LcGlyph;",
        "",
        "typedef struct {",
        "  char name[16];",
        "  uint8_t type;",
        "  uint8_t width;",
        "  uint8_t height;",
        "  size_t chars;",
        "  uint8_t data[];",
        "} LcFont;",
        "#endif",
        "",
        f"static const LcFont {symbol} = {{",
        f'  "{name[:15]}", 1, 0, {max_h}, {len(glyphs)}, {{',
    ]
    for g in glyphs:
        c = g["code"]
        ch = chr(c) if c >= 32 else " "
        if ch in ("\\", '"'):
            ch = " "
        header = [
            c & 0xFF,
            (c >> 8) & 0xFF,
            g["ofs_y"] & 0xFF,
            g["box_w"] & 0xFF,
            g["box_h"] & 0xFF,
            g["ofs_x"] & 0xFF,
            g["adv_w"] & 0xFF,
        ]
        hexes = ", ".join(f"0x{b:02X}" for b in header)
        if g["bitmap"]:
            hexes += ", " + ", ".join(f"0x{b:02X}" for b in g["bitmap"])
        lines.append(f"    /* U+{c:04X} {ch!r} */ {hexes},")
    lines += [
        "    /* terminator */ 0x00, 0x00,",
        "  },",
        "};",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, default=12)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ranges", default="32-126,160-383,416-417,432-433,7840-7929")
    ap.add_argument("--symbol", default="lc_font_data")
    ap.add_argument("--enforce", action="store_true")
    args = ap.parse_args()

    ttf = args.ttf.replace("\\:", ":")
    if not os.path.isfile(ttf):
        print(f"missing TTF: {ttf}", file=sys.stderr)
        return 1
    name, max_h, glyphs = load_glyphs(ttf, args.size, args.ranges, args.enforce)
    text = emit_c(name, args.size, max_h, glyphs, args.symbol)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out}: {len(glyphs)} glyphs, height={max_h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
